### ISSUE TITLE
Estado>>puedeTransformarse

### ISSUE THREAD

**Issue by diegosanchez** [marianoogimenez/Dragon-Ball#1]
Porqué el ```Personaje``` le preguntaría esto al ```Estado```  porqué no directamente le envía el mensaje ```estado.trasiciona() : Estado``` y este devuelve un estado nuevo.  Si no transiciona se devuelve????

**Comment by franroberti** [comment]
El problema es que para que un personaje se transforme debe cumplir ciertos requisitos. Por ejemplo, uno de los personajes puede transformarse a la primera transfomarcion solo si su vida es menor a un % de su vida máxima, y, para transformarse a la segunda, otro % de vida. Este % o condicion es propio de cada aspecto, por lo que el personaje necesita saber si cumple los requisitos necesarios para transformarse antes de cambiar su estado.

**Comment by franroberti** [comment]
Lo que se me ocurre es que, por ejemplo, Cell tenga un metodo "void transformarse(Perfecto unAspectoPerfecto)" y un "void transformarse(SemiPerfecto unAspectoSemiPerfecto)" y ahi verifique que cumple los requisitos de la transformacion. Es decir, para cada personaje implementar dos metodos "transformarse" con diferentes parametros (overload).

**Comment by vickyperezz** [comment]
ahi lo arregle, hice que directamente le diga al estado que se transforme y dependiendo de si puede o no se transforma o lanza excepcion.
