### ISSUE TITLE
consulta transformaciones

### ISSUE THREAD

**Issue by diegosanchez** [marianoogimenez/Dragon-Ball#5]
Hola Diego, estamos haciendo la vista y el controlador del TP y nos surgio una duda con respecto a las transformaciones.
Cuando hablamos el lunes nos dijiste que saquemos la lista de transformacion de cada personaje y que en vez de eso el metodo Transformar reciba ya como parametro la transformacion. 
El problema es que ahora cuando tenemos que hacer la vista, queremos mostrar para cada personaje las trasnformaciones disponibles, pero no las tenemos en ningun lado.
Donde las deberiamos guardar si no es en cada personaje?

**Comment by diegosanchez** [comment]
Qué vista tienen q crear? La del personaje? 

Cuando instancias una vista ```TransformacionXVisual``` a esta le pasas la ```TransformacionModelo```. 

Salvo que no entienda la pregunta, esto sería una forma de resolverlo.

**Comment by marianoogimenez** [comment]
Queremos que cuando seleccionemos un personaje nos aparezcan las transformaciones que podemos realizar. Algo así como esta imagen ![Transformaciones](https://user-images.githubusercontent.com/7705512/27260685-5e0d1e18-5408-11e7-9502-1f61700a54c5.png). Y la idea seria que aprietes uno de esos botones y se transforme.
